name: one_million_voices_of_agroecology_app
description: "One Million Voices of Agroecology App"
homepage: "https://onemillionvoices.agroecologymap.org"
version: 1.0.1

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  flutter_map: ^6.1.0
  flutter_map_supercluster: ^5.0.0-dev.1
  latlong2: ^0.9.0
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  flutter_login: ^5.0.0
  flutter_secure_storage: ^9.0.0
  http_interceptor: ^2.0.0-beta.8
  dart_countries: ^3.0.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  image_picker: ^1.0.7
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

funding:
 - https://ko-fi.com/agroecologymap

topics:
 - agroecology
 - permaculture
 - agroforestry
 - citizenscience
 - freesoftware
